# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-17 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.CharField(max_length=2000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irods_user', models.CharField(blank=True, max_length=30)),
                ('irods_password', models.CharField(blank=True, max_length=128)),
                ('zone', models.CharField(blank=True, max_length=128)),
                ('root', models.CharField(blank=True, max_length=128)),
                ('create_thumbs', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irodsapp.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='UserIrodsMetaDataAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_unique', models.CharField(max_length=128)),
                ('object_or_collection', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('St', 'String'), ('De', 'Decimal'), ('Da', 'Date'), ('Ti', 'Time')], default='St', max_length=3)),
                ('use_in_filters', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='userirodsmetadataattribute',
            unique_together=set([('name_unique', 'user', 'object_or_collection')]),
        ),
        migrations.AlterUniqueTogether(
            name='thumbnail',
            unique_together=set([('name', 'folder')]),
        ),
    ]
