# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irodsapp', '0002_profile_image_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='thumbnail',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='thumbnail',
            name='size',
        ),
    ]
